name: terraform-ci

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Validate each lab folder (no backend, no AWS calls, no cost)
      - name: Init/Format/Validate aws-vpc-lab
        working-directory: aws-vpc-lab
        run: |
          terraform init -backend=false
          terraform fmt -check
          terraform validate

      - name: Init/Format/Validate aws-security-group-lab
        working-directory: aws-security-group-lab
        run: |
          terraform init -backend=false
          terraform fmt -check
          terraform validate
