name: terraform-ci

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Run validation inside aws-vpc-lab folder
      - name: Terraform Init
        working-directory: aws-vpc-lab
        run: terraform init -backend=false

      - name: Terraform Format Check
        working-directory: aws-vpc-lab
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: aws-vpc-lab
        run: terraform validate
